name: Drush Security Check
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: drupal/drupal
          ref: ${{ matrix.drupal-core }}

      - name: Checkout module
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install Drupal core dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Install Coder module
        run: |
          composer --dev --no-interaction --no-progress require \
            drupal/coder:8.3.13

      - name: Run security check
        run: |
          ./vendor/bin/drush pm:security            
